# Generated by Django 4.1.1 on 2022-09-26 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Drinks', 'Drinks'), ('Desserts', 'Desserts'), ('Dinners', 'Dinners'), ('Breakfests', 'Breakfests'), ('Salads', 'Salads'), ('Healthy', 'Healthy'), ('Appetizers', 'Appetizers'), ('Instant', 'Instant')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('short_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('content_before_image', models.TextField(blank=True, null=True)),
                ('content_after_image', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('post_label', models.CharField(blank=True, choices=[('Popular', 'Popular')], max_length=255, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_api.category')),
            ],
        ),
    ]
