# Generated by Django 4.1.1 on 2022-09-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Drinks', 'Drinks'), ('Meat', 'Meat'), ('Burger', 'Burger'), ('Breakfests', 'Breakfests'), ('Salads', 'Salads'), ('Healthy', 'Healthy'), ('Appetizers', 'Appetizers'), ('Instant', 'Instant')], max_length=255),
        ),
    ]
